/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../providers/user/user.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import12 from '../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import13 from '../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import14 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import17 from '../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import18 from '../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import19 from '../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import20 from 'ionic-angular/config/config';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from 'ionic-angular/gestures/gesture-controller';
import * as import23 from 'ionic-angular/util/form';
import * as import24 from 'ionic-angular/components/app/app';
import * as import25 from 'ionic-angular/platform/platform';
import * as import26 from 'ionic-angular/components/content/content';
import * as import27 from 'ionic-angular/navigation/nav-controller';
import * as import28 from 'ionic-angular/components/label/label';
import * as import29 from '@angular/forms/src/directives/ng_model';
import * as import30 from '@angular/forms/src/directives/ng_control';
import * as import31 from '@angular/forms/src/directives/ng_control_status';
import * as import32 from 'ionic-angular/components/input/input';
import * as import33 from 'ionic-angular/components/item/item';
import * as import34 from 'ionic-angular/components/button/button';
import * as import35 from 'ionic-angular/components/list/list';
import * as import36 from '@angular/forms/src/directives/ng_form';
import * as import37 from '@angular/forms/src/directives/control_container';
export class Wrapper_LoginComponent {
  context:import0.LoginComponent;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.LoginComponent(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_LoginComponent_Host:import2.RenderComponentType = (null as any);
class _View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginComponent_0_4:Wrapper_LoginComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginComponent_Host0,renderType_LoginComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginComponent_0_4 = new Wrapper_LoginComponent(this.parentInjector.get(import8.UserService));
    this._appEl_0.initComponent(this._LoginComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginComponent_Host === (null as any))) { (renderType_LoginComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginComponentNgFactory:import10.ComponentFactory<import0.LoginComponent> = new import10.ComponentFactory<import0.LoginComponent>('login',viewFactory_LoginComponent_Host0,import0.LoginComponent);
const styles_LoginComponent:any[] = ([] as any[]);
var renderType_LoginComponent:import2.RenderComponentType = (null as any);
class _View_LoginComponent0 extends import1.AppView<import0.LoginComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _NgForm_19_3:import11.Wrapper_NgForm;
  _ControlContainer_19_4:any;
  _NgControlStatusGroup_19_5:import12.Wrapper_NgControlStatusGroup;
  _text_20:any;
  _el_21:any;
  _List_21_3:import13.Wrapper_List;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Item_23_4:import14.Wrapper_Item;
  _ItemContent_23_5:import14.Wrapper_ItemContent;
  _query_Label_23_0:import15.QueryList<any>;
  _query_Button_23_1:import15.QueryList<any>;
  _query_Icon_23_2:import15.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Label_25_3:import16.Wrapper_Label;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _NgModel_28_4:import17.Wrapper_NgModel;
  _NgControl_28_5:any;
  _NgControlStatus_28_6:import12.Wrapper_NgControlStatus;
  _TextInput_28_7:import18.Wrapper_TextInput;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _Item_31_4:import14.Wrapper_Item;
  _ItemContent_31_5:import14.Wrapper_ItemContent;
  _query_Label_31_0:import15.QueryList<any>;
  _query_Button_31_1:import15.QueryList<any>;
  _query_Icon_31_2:import15.QueryList<any>;
  _text_32:any;
  _el_33:any;
  _Label_33_3:import16.Wrapper_Label;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import3.AppElement;
  _NgModel_36_4:import17.Wrapper_NgModel;
  _NgControl_36_5:any;
  _NgControlStatus_36_6:import12.Wrapper_NgControlStatus;
  _TextInput_36_7:import18.Wrapper_TextInput;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _Button_41_4:import19.Wrapper_Button;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginComponent0,renderType_LoginComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'h3',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Login to see some stuff using these creds:',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'dl',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'dt',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Email:',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'dd',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'cave@aperture.com',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_4,'dt',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Password:',(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_4,'dd',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'notneverbutnow',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_19 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this._NgForm_19_3 = new import11.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_19_4 = this._NgForm_19_3.context;
    this._NgControlStatusGroup_19_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_19_4);
    this._text_20 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'ion-list',(null as any));
    this._List_21_3 = new import13.Wrapper_List(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_21),this.renderer,this.parentInjector.get(import22.GestureController));
    this._text_22 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this._appEl_23 = new import3.AppElement(23,21,this,this._el_23);
    var compView_23:any = import14.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import14.Wrapper_Item(this.parentInjector.get(import23.Form),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_23),this.renderer);
    this._ItemContent_23_5 = new import14.Wrapper_ItemContent();
    this._query_Label_23_0 = new import15.QueryList<any>();
    this._query_Button_23_1 = new import15.QueryList<any>();
    this._query_Icon_23_2 = new import15.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_25,'stacked','');
    this._Label_25_3 = new import16.Wrapper_Label(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_25),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Email',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_28,'name','userEmail');
    this.renderer.setElementAttribute(this._el_28,'type','email');
    this._appEl_28 = new import3.AppElement(28,23,this,this._el_28);
    var compView_28:any = import18.viewFactory_TextInput0(this.viewUtils,this.injector(28),this._appEl_28);
    this._NgModel_28_4 = new import17.Wrapper_NgModel(this._ControlContainer_19_4,(null as any),(null as any),(null as any));
    this._NgControl_28_5 = this._NgModel_28_4.context;
    this._NgControlStatus_28_6 = new import12.Wrapper_NgControlStatus(this._NgControl_28_5);
    this._TextInput_28_7 = new import18.Wrapper_TextInput(this.parentInjector.get(import20.Config),this.parentInjector.get(import23.Form),this._Item_23_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import25.Platform),new import21.ElementRef(this._el_28),this.renderer,this.parentInjector.get(import26.Content,(null as any)),this.parentInjector.get(import27.NavController,(null as any)),this._NgControl_28_5);
    this._appEl_28.initComponent(this._TextInput_28_7.context,([] as any[]),compView_28);
    compView_28.create(this._TextInput_28_7.context,([] as any[]),(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_23_0.reset([this._Label_25_3.context]);
    this._Item_23_4.context.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_25]),
      ([] as any[]).concat([
        this._text_24,
        this._text_27,
        this._text_29
      ]
      ),
      ([] as any[]).concat([this._el_28]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_30 = this.renderer.createText(this._el_21,'\n\n            ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_21,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','item item-block');
    this._appEl_31 = new import3.AppElement(31,21,this,this._el_31);
    var compView_31:any = import14.viewFactory_Item0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Item_31_4 = new import14.Wrapper_Item(this.parentInjector.get(import23.Form),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_31),this.renderer);
    this._ItemContent_31_5 = new import14.Wrapper_ItemContent();
    this._query_Label_31_0 = new import15.QueryList<any>();
    this._query_Button_31_1 = new import15.QueryList<any>();
    this._query_Icon_31_2 = new import15.QueryList<any>();
    this._appEl_31.initComponent(this._Item_31_4.context,([] as any[]),compView_31);
    this._text_32 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_33,'stacked','');
    this._Label_33_3 = new import16.Wrapper_Label(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_33),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Password',(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_36,'name','userPassword');
    this.renderer.setElementAttribute(this._el_36,'type','password');
    this._appEl_36 = new import3.AppElement(36,31,this,this._el_36);
    var compView_36:any = import18.viewFactory_TextInput0(this.viewUtils,this.injector(36),this._appEl_36);
    this._NgModel_36_4 = new import17.Wrapper_NgModel(this._ControlContainer_19_4,(null as any),(null as any),(null as any));
    this._NgControl_36_5 = this._NgModel_36_4.context;
    this._NgControlStatus_36_6 = new import12.Wrapper_NgControlStatus(this._NgControl_36_5);
    this._TextInput_36_7 = new import18.Wrapper_TextInput(this.parentInjector.get(import20.Config),this.parentInjector.get(import23.Form),this._Item_31_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import25.Platform),new import21.ElementRef(this._el_36),this.renderer,this.parentInjector.get(import26.Content,(null as any)),this.parentInjector.get(import27.NavController,(null as any)),this._NgControl_36_5);
    this._appEl_36.initComponent(this._TextInput_36_7.context,([] as any[]),compView_36);
    compView_36.create(this._TextInput_36_7.context,([] as any[]),(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_31_0.reset([this._Label_33_3.context]);
    this._Item_31_4.context.contentLabel = this._query_Label_31_0.first;
    compView_31.create(this._Item_31_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_33]),
      ([] as any[]).concat([
        this._text_32,
        this._text_35,
        this._text_37
      ]
      ),
      ([] as any[]).concat([this._el_36]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_38 = this.renderer.createText(this._el_21,'\n\n            ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_21,'hr',(null as any));
    this._text_40 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_21,'button',(null as any));
    this.renderer.setElementAttribute(this._el_41,'ion-button','');
    this.renderer.setElementAttribute(this._el_41,'type','submit');
    this._appEl_41 = new import3.AppElement(41,21,this,this._el_41);
    var compView_41:any = import19.viewFactory_Button0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Button_41_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_41),this.renderer);
    this._appEl_41.initComponent(this._Button_41_4.context,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'Login!',(null as any));
    compView_41.create(this._Button_41_4.context,[([] as any[]).concat([this._text_42])],(null as any));
    this._text_43 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_19,'ngSubmit',this.eventHandler(this._handle_ngSubmit_19_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_19,'submit',this.eventHandler(this._handle_submit_19_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_19,'reset',this.eventHandler(this._handle_reset_19_2.bind(this)));
    const subscription_0:any = this._NgForm_19_3.context.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_19_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_28,'ngModelChange',this.eventHandler(this._handle_ngModelChange_28_0.bind(this)));
    const subscription_1:any = this._NgModel_28_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_28_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_36,'ngModelChange',this.eventHandler(this._handle_ngModelChange_36_0.bind(this)));
    const subscription_2:any = this._NgModel_36_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_36_0.bind(this)));
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.Label) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Label_25_3.context; }
    if (((token === import29.NgModel) && (28 === requestNodeIndex))) { return this._NgModel_28_4.context; }
    if (((token === import30.NgControl) && (28 === requestNodeIndex))) { return this._NgControl_28_5; }
    if (((token === import31.NgControlStatus) && (28 === requestNodeIndex))) { return this._NgControlStatus_28_6.context; }
    if (((token === import32.TextInput) && (28 === requestNodeIndex))) { return this._TextInput_28_7.context; }
    if (((token === import33.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Item_23_4.context; }
    if (((token === import33.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ItemContent_23_5.context; }
    if (((token === import28.Label) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Label_33_3.context; }
    if (((token === import29.NgModel) && (36 === requestNodeIndex))) { return this._NgModel_36_4.context; }
    if (((token === import30.NgControl) && (36 === requestNodeIndex))) { return this._NgControl_36_5; }
    if (((token === import31.NgControlStatus) && (36 === requestNodeIndex))) { return this._NgControlStatus_36_6.context; }
    if (((token === import32.TextInput) && (36 === requestNodeIndex))) { return this._TextInput_36_7.context; }
    if (((token === import33.Item) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Item_31_4.context; }
    if (((token === import33.ItemContent) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ItemContent_31_5.context; }
    if (((token === import34.Button) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Button_41_4.context; }
    if (((token === import35.List) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._List_21_3.context; }
    if (((token === import36.NgForm) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._NgForm_19_3.context; }
    if (((token === import37.ControlContainer) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._ControlContainer_19_4; }
    if (((token === import31.NgControlStatusGroup) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._NgControlStatusGroup_19_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    this._NgControlStatusGroup_19_5.detectChangesInternal(this,this._el_19,throwOnChange);
    this._List_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    if (this._Item_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._ItemContent_23_5.detectChangesInternal(this,this._el_23,throwOnChange);
    this._Label_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_10:any = 'userEmail';
    this._NgModel_28_4.check_name(currVal_10,throwOnChange,false);
    const currVal_11:any = this.context.userEmail;
    this._NgModel_28_4.check_model(currVal_11,throwOnChange,false);
    this._NgModel_28_4.detectChangesInternal(this,this._el_28,throwOnChange);
    this._NgControlStatus_28_6.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_18:any = 'email';
    this._TextInput_28_7.check_type(currVal_18,throwOnChange,false);
    this._TextInput_28_7.detectChangesInternal(this,this._el_28,throwOnChange);
    if (this._Item_31_4.detectChangesInternal(this,this._el_31,throwOnChange)) { this._appEl_31.componentView.markAsCheckOnce(); }
    this._ItemContent_31_5.detectChangesInternal(this,this._el_31,throwOnChange);
    this._Label_33_3.detectChangesInternal(this,this._el_33,throwOnChange);
    const currVal_20:any = 'userPassword';
    this._NgModel_36_4.check_name(currVal_20,throwOnChange,false);
    const currVal_21:any = this.context.userPassword;
    this._NgModel_36_4.check_model(currVal_21,throwOnChange,false);
    this._NgModel_36_4.detectChangesInternal(this,this._el_36,throwOnChange);
    this._NgControlStatus_36_6.detectChangesInternal(this,this._el_36,throwOnChange);
    const currVal_28:any = 'password';
    this._TextInput_36_7.check_type(currVal_28,throwOnChange,false);
    this._TextInput_36_7.detectChangesInternal(this,this._el_36,throwOnChange);
    if (this._Button_41_4.detectChangesInternal(this,this._el_41,throwOnChange)) { this._appEl_41.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset(([] as any[]));
        this._Item_23_4.context._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset(([] as any[]));
        this._Item_23_4.context._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_31_1.dirty) {
        this._query_Button_31_1.reset(([] as any[]));
        this._Item_31_4.context._buttons = this._query_Button_31_1;
        this._query_Button_31_1.notifyOnChanges();
      }
      if (this._query_Icon_31_2.dirty) {
        this._query_Icon_31_2.reset(([] as any[]));
        this._Item_31_4.context._icons = this._query_Icon_31_2;
        this._query_Icon_31_2.notifyOnChanges();
      }
      this._TextInput_28_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_23_4.context.ngAfterContentInit(); }
      this._TextInput_36_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_31_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_41_4.context.ngAfterContentInit(); }
    }
    const currVal_3:any = this._NgControlStatusGroup_19_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_19_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_19_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_19_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_19_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_19_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_12:any = this._NgControlStatus_28_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_28,'ng-untouched',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_28_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_28,'ng-touched',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_28_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_28,'ng-pristine',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_28_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_28,'ng-dirty',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_28_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_28,'ng-valid',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_28_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_28,'ng-invalid',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_22:any = this._NgControlStatus_36_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_36,'ng-untouched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_36_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_36,'ng-touched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_36_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_36,'ng-pristine',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_36_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_36,'ng-dirty',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_36_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_36,'ng-valid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_36_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_36,'ng-invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_28_4.context.ngOnDestroy();
    this._TextInput_28_7.context.ngOnDestroy();
    this._NgModel_36_4.context.ngOnDestroy();
    this._TextInput_36_7.context.ngOnDestroy();
  }
  private _handle_ngSubmit_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.login()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_19_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_19_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_19_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_19_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.userEmail = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_36_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.userPassword = $event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginComponent> {
  if ((renderType_LoginComponent === (null as any))) { (renderType_LoginComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_LoginComponent,{})); }
  return new _View_LoginComponent0(viewUtils,parentInjector,declarationEl);
}