/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './logout.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import10 from '@angular/core/src/linker/component_factory';
export declare class Wrapper_LogoutComponent {
    context: import0.LogoutComponent;
    changed: boolean;
    constructor(p0: any);
    detectChangesInternal(view: import1.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare const LogoutComponentNgFactory: import10.ComponentFactory<import0.LogoutComponent>;
export declare function viewFactory_LogoutComponent0(viewUtils: import5.ViewUtils, parentInjector: import6.Injector, declarationEl: import3.AppElement): import1.AppView<import0.LogoutComponent>;
