/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './home';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import15 from 'ionic-angular/config/config';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from 'ionic-angular/navigation/view-controller';
import * as import18 from 'ionic-angular/components/app/app';
import * as import19 from 'ionic-angular/components/toolbar/toolbar';
import * as import20 from 'ionic-angular/util/keyboard';
import * as import21 from '@angular/core/src/zone/ng_zone';
import * as import22 from 'ionic-angular/components/tabs/tabs';
import * as import23 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import24 from 'ionic-angular/components/navbar/navbar';
import * as import25 from 'ionic-angular/components/content/content';
export class Wrapper_HomePage {
  context:import0.HomePage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.HomePage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_HomePage_Host:import2.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HomePage_0_4:Wrapper_HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new Wrapper_HomePage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._HomePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._HomePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HomePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import10.ComponentFactory<import0.HomePage> = new import10.ComponentFactory<import0.HomePage>('page-home',viewFactory_HomePage_Host0,import0.HomePage);
const styles_HomePage:any[] = ([] as any[]);
var renderType_HomePage:import2.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import0.HomePage> {
  _el_0:any;
  _Header_0_3:import11.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import12.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import13.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import14.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _el_102:any;
  _text_103:any;
  _el_104:any;
  _text_105:any;
  _text_106:any;
  _text_107:any;
  _text_108:any;
  _text_109:any;
  _text_110:any;
  _text_111:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Wrapper_Header(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import17.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import18.App),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import13.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import13.Wrapper_ToolbarTitle(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import19.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Intro',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import14.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import14.Wrapper_Content(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import18.App),this.parentInjector.get(import20.Keyboard),this.parentInjector.get(import21.NgZone),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import22.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'h1',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Firebase in Angular 2',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'If you\'re interested in the files that I\'ve changed to integrate Firebase and get this simple auth example\n        working, they\'re:',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ul',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'li',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'strong',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'providers/data/data.service.ts',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,' - sets up Firebase database references\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_17,'li',(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'strong',(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'providers/user/user.service.ts',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,' - abstracts Firebase auth methods\n        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_17,'li',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'strong',(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'pages/home/',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,' - the currently active component\n            ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_31,'ul',(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'li',(null as any));
    this._el_39 = this.renderer.createElement(this._el_38,'strong',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'home.html',(null as any));
    this._text_41 = this.renderer.createText(this._el_38,' - the template you\'re currently viewing',(null as any));
    this._text_42 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._text_43 = this.renderer.createText(this._el_31,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_17,'li',(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'strong',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'pages/basic-demo/',(null as any));
    this._text_49 = this.renderer.createText(this._el_45,' - basic database demo\n            ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_45,'ul',(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_50,'li',(null as any));
    this._el_53 = this.renderer.createElement(this._el_52,'strong',(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'basic-demo.html',(null as any));
    this._text_55 = this.renderer.createText(this._el_52,' - sets up the template for displaying synced data',(null as any));
    this._text_56 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_50,'li',(null as any));
    this._el_58 = this.renderer.createElement(this._el_57,'strong',(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'basic-demo.ts',(null as any));
    this._text_60 = this.renderer.createText(this._el_57,' - builds out the @Page for displaying synced data',(null as any));
    this._text_61 = this.renderer.createText(this._el_50,'\n            ',(null as any));
    this._text_62 = this.renderer.createText(this._el_45,'\n        ',(null as any));
    this._text_63 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_17,'li',(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'\n            ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_64,'strong',(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'pages/auth/',(null as any));
    this._text_68 = this.renderer.createText(this._el_64,' - Firebase authentication demo\n            ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_64,'ul',(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'\n                ',(null as any));
    this._el_71 = this.renderer.createElement(this._el_69,'li',(null as any));
    this._el_72 = this.renderer.createElement(this._el_71,'strong',(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'auth.html',(null as any));
    this._text_74 = this.renderer.createText(this._el_71,' - sets up the template for displaying user auth states',(null as any));
    this._text_75 = this.renderer.createText(this._el_69,'\n                ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_69,'li',(null as any));
    this._el_77 = this.renderer.createElement(this._el_76,'strong',(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'auth.ts',(null as any));
    this._text_79 = this.renderer.createText(this._el_76,' - builds out the @Page for integrating user auth states',(null as any));
    this._text_80 = this.renderer.createText(this._el_69,'\n            ',(null as any));
    this._text_81 = this.renderer.createText(this._el_64,'\n        ',(null as any));
    this._text_82 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_83 = this.renderer.createElement(this._el_17,'li',(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'\n            ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_83,'strong',(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'pages/tabs/tabs.html',(null as any));
    this._text_87 = this.renderer.createText(this._el_83,' - revised tab titles\n        ',(null as any));
    this._text_88 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_89 = this.renderer.createElement(this._el_17,'li',(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'\n            ',(null as any));
    this._el_91 = this.renderer.createElement(this._el_89,'strong',(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'components/',(null as any));
    this._text_93 = this.renderer.createText(this._el_89,' - components used for interacting with auth states\n            ',(null as any));
    this._el_94 = this.renderer.createElement(this._el_89,'ul',(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'\n                ',(null as any));
    this._el_96 = this.renderer.createElement(this._el_94,'li',(null as any));
    this._text_97 = this.renderer.createText(this._el_96,'\n                    ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_96,'strong',(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'login.component.ts',(null as any));
    this._text_100 = this.renderer.createText(this._el_96,' - builds the login form, integrates the user service login\n                    function\n                ',(null as any));
    this._text_101 = this.renderer.createText(this._el_94,'\n                ',(null as any));
    this._el_102 = this.renderer.createElement(this._el_94,'li',(null as any));
    this._text_103 = this.renderer.createText(this._el_102,'\n                    ',(null as any));
    this._el_104 = this.renderer.createElement(this._el_102,'strong',(null as any));
    this._text_105 = this.renderer.createText(this._el_104,'logout.component.ts',(null as any));
    this._text_106 = this.renderer.createText(this._el_102,' - allows the user to logout, resetting the view to display the login form\n                ',(null as any));
    this._text_107 = this.renderer.createText(this._el_94,'\n            ',(null as any));
    this._text_108 = this.renderer.createText(this._el_89,'\n        ',(null as any));
    this._text_109 = this.renderer.createText(this._el_17,'\n\n    ',(null as any));
    this._text_110 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_16,
        this._el_17,
        this._text_110
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_111 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._text_106,
      this._text_107,
      this._text_108,
      this._text_109,
      this._text_110,
      this._text_111
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import24.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import19.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import25.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 110)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.context.ngOnDestroy();
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}