/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './auth';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../providers/data/data.service';
import * as import9 from '../../providers/user/user.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import17 from 'ionic-angular/config/config';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from 'ionic-angular/navigation/view-controller';
import * as import20 from 'ionic-angular/components/app/app';
import * as import21 from 'ionic-angular/navigation/nav-controller';
import * as import22 from 'ionic-angular/components/toolbar/toolbar';
import * as import23 from 'ionic-angular/util/keyboard';
import * as import24 from '@angular/core/src/zone/ng_zone';
import * as import25 from 'ionic-angular/components/tabs/tabs';
import * as import26 from '@angular/core/src/linker/template_ref';
import * as import27 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import28 from 'ionic-angular/components/navbar/navbar';
import * as import29 from '@angular/common/src/directives/ng_if';
import * as import30 from 'ionic-angular/components/content/content';
import * as import31 from '../../components/login.component.ngfactory';
import * as import32 from '../../components/login.component';
import * as import33 from '../../components/logout.component.ngfactory';
import * as import34 from '../../components/logout.component';
export class Wrapper_AuthPage {
  context:import0.AuthPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.AuthPage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_AuthPage_Host:import2.RenderComponentType = (null as any);
class _View_AuthPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AuthPage_0_4:Wrapper_AuthPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AuthPage_Host0,renderType_AuthPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AuthPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AuthPage_0_4 = new Wrapper_AuthPage(this.parentInjector.get(import8.DataService),this.parentInjector.get(import9.UserService),compView_0.ref);
    this._appEl_0.initComponent(this._AuthPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AuthPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AuthPage) && (0 === requestNodeIndex))) { return this._AuthPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AuthPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AuthPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AuthPage_Host === (null as any))) { (renderType_AuthPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AuthPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const AuthPageNgFactory:import11.ComponentFactory<import0.AuthPage> = new import11.ComponentFactory<import0.AuthPage>('ng-component',viewFactory_AuthPage_Host0,import0.AuthPage);
const styles_AuthPage:any[] = ([] as any[]);
var renderType_AuthPage:import2.RenderComponentType = (null as any);
class _View_AuthPage0 extends import1.AppView<import0.AuthPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import12.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import13.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import14.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import15.Wrapper_Content;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import16.Wrapper_NgIf;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import16.Wrapper_NgIf;
  _text_15:any;
  _text_16:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AuthPage0,renderType_AuthPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import12.Wrapper_Header(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import19.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import20.App),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import21.NavController,(null as any)),this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import14.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import14.Wrapper_ToolbarTitle(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import22.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n            Authentication Demo\n        ',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','page3');
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import15.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import15.Wrapper_Content(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import20.App),this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import24.NgZone),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import25.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n	',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_12 = new import3.AppElement(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import26.TemplateRef_(this._appEl_12,viewFactory_AuthPage1);
    this._NgIf_12_6 = new import16.Wrapper_NgIf(this._appEl_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText((null as any),'\n	',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_14 = new import3.AppElement(14,10,this,this._anchor_14);
    this._TemplateRef_14_5 = new import26.TemplateRef_(this._appEl_14,viewFactory_AuthPage2);
    this._NgIf_14_6 = new import16.Wrapper_NgIf(this._appEl_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._appEl_12,
        this._text_13,
        this._appEl_14,
        this._text_15
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._text_16
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import28.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import22.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import26.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import29.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6.context; }
    if (((token === import26.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import29.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    if (((token === import30.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_3:boolean = !this.context.authStatus;
    this._NgIf_12_6.check_ngIf(currVal_3,throwOnChange,false);
    this._NgIf_12_6.detectChangesInternal(this,this._anchor_12,throwOnChange);
    const currVal_4:any = this.context.authStatus;
    this._NgIf_14_6.check_ngIf(currVal_4,throwOnChange,false);
    this._NgIf_14_6.detectChangesInternal(this,this._anchor_14,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.context.ngOnDestroy();
  }
}
export function viewFactory_AuthPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AuthPage> {
  if ((renderType_AuthPage === (null as any))) { (renderType_AuthPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_AuthPage,{})); }
  return new _View_AuthPage0(viewUtils,parentInjector,declarationEl);
}
class _View_AuthPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginComponent_0_4:import31.Wrapper_LoginComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AuthPage1,renderType_AuthPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'login',(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import31.viewFactory_LoginComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginComponent_0_4 = new import31.Wrapper_LoginComponent(this.parent.parentInjector.get(import9.UserService));
    this._appEl_0.initComponent(this._LoginComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginComponent_0_4.context,([] as any[]),(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AuthPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AuthPage1(viewUtils,parentInjector,declarationEl);
}
class _View_AuthPage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _UserService_12_4:import9.UserService;
  _LogoutComponent_12_5:import33.Wrapper_LogoutComponent;
  _text_13:any;
  _text_14:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AuthPage2,renderType_AuthPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h3',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Nicely done!',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'p',(null as any));
    this._el_6 = this.renderer.createElement(this._el_5,'strong',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Your private message:',(null as any));
    this._text_8 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_10 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._text_11 = this.renderer.createText(this._el_10,'\n			',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'logout',(null as any));
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import33.viewFactory_LogoutComponent0(this.viewUtils,this.injector(12),this._appEl_12);
    this._UserService_12_4 = new import9.UserService();
    this._LogoutComponent_12_5 = new import33.Wrapper_LogoutComponent(this._UserService_12_4);
    this._appEl_12.initComponent(this._LogoutComponent_12_5.context,([] as any[]),compView_12);
    compView_12.create(this._LogoutComponent_12_5.context,([] as any[]),(null as any));
    this._text_13 = this.renderer.createText(this._el_10,'\n		',(null as any));
    this._text_14 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.UserService) && (12 === requestNodeIndex))) { return this._UserService_12_4; }
    if (((token === import34.LogoutComponent) && (12 === requestNodeIndex))) { return this._LogoutComponent_12_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LogoutComponent_12_5.detectChangesInternal(this,this._el_12,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' ',this.parent.context.message,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_8,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AuthPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AuthPage2(viewUtils,parentInjector,declarationEl);
}